Dev
WildCodeSchool-2024-02/JS-lyon-0224-P2-martian_meteorologists_association pull request #28
Opened 2024-04-25 15:02 UTC by rostom44

15 Pop-up de formulaire
23 améliorer le code des icônes de la météo
22 - Prix en fonction des choix - formulaire de réservation
20 choix des acitvités en fonction des préférences_ page activités
21 ajouter modèles 3D de vaisseaux - page réservation
16 CSS page formulaire
19 css page activies

trello : https://trello.com/b/M3m8zZtz/nasa-mma

2024-04-26 07:47 UTC, HazeFury commented on client/src/BDD/Activities.jsx
Pour faire un tableau de données, envisager de passer plutôt par un format JSON qui correspond complètement à ce que vous voulez faire.
L'avantage est que le format est beaucoup plus léger que le JSX. De plus, pourquoi utiliser le JSX alors que vous n'utilisez aucun élément de react et ne rendez rien de visuelle ??

Donc l'extension du fichier doit changer en "Activities.json" et il faut adapter le contenu ^^

2024-04-26 07:50 UTC, HazeFury commented on client/src/BDD/ShuttleCards.jsx
> +import Premuim from "../components/ReservationPage/Reservation/Premium";
Pour chipoter un peu mais je pense que c'est censé être "Premium" et non "Premuim" 😉

2024-04-26 08:01 UTC, HazeFury commented on client/src/Contexts/IndexCurrentWeather.jsx
> +          switch (true) {
Alors globalement c'est très bien ce m'as fait.
Le seule truc que je pourrais dire, c'est que ce serait bien de faire une fonction a part pour ton switch case pour pas trop chargé ton useEffect et être un peu plus lisible mais c'est du détail 😃

2024-04-26 08:07 UTC, HazeFury commented on client/src/components/Acitvities/ActivitiesComponents/Activities.jsx
> +    const tbl = [];
Encore un peu de chipotage mais "tbl" pour tableau j'imagine ^^ 
Ne mettez pas de nom en français => anglais uniquement !!

donc array pour un tableau, soit "arr" si voulez raccourcir 😉

2024-04-26 08:27 UTC, HazeFury commented on client/src/components/ReservationPage/Reservation/Reservation.css
> +  width: 80vw !important;
Je dis rien pour celle-là car j'imagine que c'est lié au canva pour afficher la planète ou les vaisseaux et c'est un peu particulier à gérer.
Mais en général, il faut éviter les "!important" . Si vous êtes obligés de vous en servir, dans 9 chances sur 10, c'est que vous n'avez pas utiliser les bonne règles CSS => il faut trouver les bonnes règles pour ne pas avoir à l'utiliser

2024-04-26 08:38 UTC, HazeFury approved these changes
Bah c'est du très bon boulot tout ça, BRAVO 👍 💯 

Des petits trucs mineures à corriger ici et là mais rien de méchant ^^

2024-04-26 09:29 UTC, wildmatthieu requested changes

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/public/ship/shuttle3/license.txt
> +* requirements:	Author must be credited. Commercial use is allowed.
est-ce que l'auteur est crédité sur l'application ?

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/pages/HomePage.jsx
> +  if (!weatherData) {
explicitez vos conditions : 
weatherData

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/pages/ActivitiesPage.jsx
> +  if (!weatherData) {
explicitez vos conditions : 
weatherData

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/components/ReservationForm/PopUp.jsx
> +      {popUp && (
explicitez les conditions : 
popUp === ? &&

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/components/ReservationForm/PopUp.css
> +/* body.active-popUp {
code mort => à retirer !

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/components/HomePage/CurrentWeather/CurrentWeather.css
>    height: 15vh !important;
l'utilisation de !important est à faire en cas de dernière solution / ultime recours 
=> pouvez vous vérifier que les !importans soient vraiment nécassaires ?

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/BDD/ShuttleCards.jsx
> +import Premuim from "../components/ReservationPage/Reservation/Premium";
typo à corriger en effet !

2024-04-26 09:29 UTC, wildmatthieu commented on client/src/BDD/Activities.jsx
Alors coté JSON c'est pas forcement plus opti : 
- en effet : des données, structurées en format JSON, donnent un fichier très léger
- mais... ! ici les données sont directement écrites en JS 

Donc le format JSON léger => oui
Mais, pour le faire faire manipuler par du javascript, il faut donc importer le fichier json , javascript doit le transformer en interne pour pouvoir traiter le fichier (qui est un fichier texte en soi) : ces opérations seront plus couteuses du coup 

Par contre, utiliser un fichier .JSX dans lequel on n'utilise pas de JSX (ce fichier se contente d'instancier une structure de données en javascript) n'est pas nécessaire. Donc ce fichier peux être renommé avec lextension .js

2024-04-26 09:41 UTC, CharlotteR678 commented on client/src/components/HomePage/CurrentWeather/CurrentWeather.css
>    height: 15vh !important;
On pense que c'est nécessaire, si on l'enlève tout bug et on n'a pas trouvé de solution pour ça (hors important)

2024-04-29 10:06 UTC, wildmatthieu requested changes

2024-04-29 10:06 UTC, wildmatthieu commented on client/src/Contexts/IndexCurrentWeather.jsx
> +          const day = APIweather.current.is_day ? "day" : "night";
explicitez les conditions : 
APIweather.current.is_day === ?

2024-04-29 10:06 UTC, wildmatthieu commented on client/src/components/Acitvities/ActivitiesComponents/Activities.jsx
> +        item.category.includes(feelValue) &&
```
        item.category.includes(feelValue) &&
        item.category.includes(sportValue) &&
        item.category.includes(WeatherLogo[currentWeather].name)
```
explicitez vos conditions : 

item.category.includes(feelValue) === ?
item.category.includes(sportValue) === ?
item.category.includes(WeatherLogo[currentWeather].name) === ?

2024-04-29 10:06 UTC, wildmatthieu commented on client/src/components/Acitvities/ActivitiesComponents/Activities.jsx
> +      if (!arr.includes(nbRandom)) {
explicitez la condition : 
`!arr.includes(nbRandom) === ?`

2024-04-29 10:06 UTC, wildmatthieu commented on client/src/components/ReservationForm/ReservationForm.jsx
> +      allDetails.user_email.includes("@") &&
explicitez les conditions : 
allDetails.user_email.includes("@") === ? 
allDetails.user_email.includes(".") === ?

2024-04-29 11:23 UTC, wildmatthieu approved these changes

2024-04-29 11:24 UTC, merged